import  { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Sidebar from "@/layouts/Sidebar";
import Followbar from "@/layouts/Followbar";
import ToasterProvider from "@/context/ToasterProvider";
import AuthProvider from "@/context/AuthProvider";
import OnlineStatus from "@/context/OnlineStatus";

const poppins = Poppins({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-poppins",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata = {
  title: "EX-Clone",
  description: "Generated by create next app",
};

export default function RootLayout() {
  return (
    <html lang="en">
      <body className={`${poppins.className} bg-black`}>
        <div className="flex h-screen overflow-y-hidden">
          <AuthProvider>
          <Sidebar />
          <ToasterProvider />
          <OnlineStatus />
          {children}
          <Followbar />
          </AuthProvider>
        </div>
      </body>
    </html>
  );
}
// pl-16 pr-16